### ISSUE TITLE
GFM 支持

### ISSUE THREAD

**Issue by jiyinyiyong** [HaskellCNOrg/snap-web#29]
原生的 Markdown 太难用了. 建议跟 GitHub Issue 同步.
不清楚 Haskell 是否有 GFM 实现..

**Comment by freizl** [comment]
我记得Haskell的实现和GFW有一定兼容性的。
能说下大概你遇到哪些问题？

**Comment by jiyinyiyong** [comment]
* 链接不会自动标记
* 换行风格不方便日常回复
* 标记代码需要额外的缩进

真的要在上边写东西, 这些体验还是挺烦人的.

**Comment by freizl** [comment]
1和2确实有点不方便，特别是2吧。
代码应该支持GFM的方式？
https://help.github.com/articles/github-flavored-markdown/
> Fenced code blocks
