### ISSUE TITLE
请问网站需要继续维护吗？

### ISSUE THREAD

**Issue by kalxd** [HaskellCNOrg/snap-web#35]
中文社区找不到可以讨论地方，这里算是最后的站点了吧，所以我想尝试维护下去。

因为Haskell非常不熟，在ghc-8.0.1上不知道如何正常运行起来。

**Comment by freizl** [comment]
ghc8 可能不行，估计需要升级许多包。。
有兴趣的话可以结合[stack](https://www.haskellstack.org/)

尝试了下 ghc7.8 还是 少很多包而且还需要升级版本，当初这个程序是在ghc7.4 开发的。
https://github.com/HaskellCNOrg/snap-web/commit/1bda5aab6a1bc447300f4dd01b4fcfd895f9c3de

一直没太有时间专注维护，欢迎参与！！

**Comment by kalxd** [comment]
你好，今天稍微试了一下，`stack init`给出的几个resolver都不合适，看来得手动处理了，暂时移到extra-deps。

`.travis.yaml`刚好记录了ghc的版本。如果需要升级的话，都升级到最新是否合适？

另，我用docker做开发，切换ghc版本还算比较容易吧。

（没注意你的提交，原来已经升级好了。=w=

**Comment by freizl** [comment]
我倒没有用docker，stack和docker集成貌似简单的，stack切换版本也蛮容易。

Resolver不会自动生成，因为包的关系，要生成后自己再加包

我还没升级好 还差一个包 snap-mongodb-min 这个好久没人维护了 需要升级才能兼容ghc78

**Comment by freizl** [comment]
[代码在这](https://github.com/HaskellCNOrg/snaplet-mongodb-minimalistic/tree/upgrade-stack-lts-3.22)
现在看来主要是要升级到[mongodb binding](https://hackage.haskell.org/package/mongoDB) 2.x 较之前1.x有些变化。。。有兴趣可以试试，感觉需要花点时间。

我现在是想先升级到ghc7.8 希望会简单些以及希望不会破环功能。
然后再尝试ghc8 希望会更加顺利些。

any thoughts？

**Comment by kalxd** [comment]
刚上手的缘故，所以对于我来说升级到哪个版本都一样的。那么可以尝试升到最新，现有代码量不是很多，做出调整比较容易。

因为我是Haskell新人，这种更改成本多高不了解，这样做相当于重构了一次，渐进升级也是个好方法。

**Comment by freizl** [comment]
@kalxd 好的 你试试升级到最新 ？[stack lts7.13](https://www.stackage.org/lts-7.13) ?
是的 主要是有些依赖包过时得升级 有些工作量。。😄

**Comment by freizl** [comment]
@kalxd 移步到这个帖子 https://github.com/HaskellCNOrg/snap-web/issues/36

**Comment by freizl** [comment]
_close this and track in an follow up ticket._
